#region License

// Copyright (c) 2013 HTW Berlin
// All rights reserved.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: Guid("0c3528eb-ed8b-4cc9-b3bc-b50423cd5be0")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfiguration("debug")]
[assembly: AssemblyCompany("HTW Berlin")]
[assembly: AssemblyProduct("Milan.Simulation.ShiftSystems.UI")]
[assembly: AssemblyCopyright("Copyright © 2013 HTW Berlin")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyTitle("Milan.Simulation.ShiftSystems.UI")]
[assembly: AssemblyDescription("")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]