#region License

// Copyright (c) 2013 HTW Berlin
// All rights reserved.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: Guid("9f48eaf3-54d2-405e-b6c5-81575ea59c63")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfiguration("debug")]
[assembly: AssemblyCompany("HTW Berlin")]
[assembly: AssemblyProduct("Milan.Simulation.ShiftSystems.Tests")]
[assembly: AssemblyCopyright("Copyright © 2013 HTW Berlin")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyTitle("Milan.Simulation.ShiftSystems.Tests")]
[assembly: AssemblyDescription("")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]