#region License

// Copyright (c) 2013 HTW Berlin
// All rights reserved.

#endregion

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("6c56e0d5-d61d-4cd4-bf80-63f7e0f0cde3")]
[assembly: ComVisible(false)]
[assembly: AssemblyConfiguration("debug")]
[assembly: AssemblyCompany("HTW Berlin")]
[assembly: AssemblyProduct("Milan.Simulation.MaterialAccounting")]
[assembly: AssemblyCopyright("Copyright © 2013 HTW Berlin")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyTitle("Milan.Simulation.MaterialAccounting")]
[assembly: AssemblyDescription("")]
[assembly: NeutralResourcesLanguage("en-US")]
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: InternalsVisibleTo("Milan.Simulation.MaterialAccounting.Tests")]
[assembly: AssemblyFileVersion("0.1.0.0")]